### PR TITLE
Fix rate limiting

### PR DESCRIPTION
**Pull request by Missing-Tech**

### CODE REVIEW

**Comment by Missing-Tech** [comment]
@kvz @arnaudlimbourg Could you take a look at this one please? Fixes #13

**Comment by Missing-Tech** [comment]
Yup it looks like that's exactly what was happening, not sure how it wasn't hitting the rate limiter before.

**Comment by kvz** [comment]
@ifedapoolarewaju perhaps you can help us release this?

**Comment by ifedapoolarewaju** [comment]
Sure, I can do this before EoD today

**Comment by tim-kos** [comment]
> Yup it looks like that's exactly what was happening, not sure how it wasn't hitting the rate limiter before.

We had a problem recently after async/awaitifying where the results of the rate limiter weren't properly checked. That is very likely why. 👍

**Comment by kvz** [comment]
Awesome Ife! Could you perhaps also document how it is done? Then we needn’t bother you anymore with this 👌

**Comment by ifedapoolarewaju** [comment]
Hi, before I go ahead to release this, I'd like to confirm that we've tested that this works right? I ask because we are setting it to sleep for `0.2` seconds after each iteration, which is quite meagre and pretty close to 0 seconds. So I wonder if this value will be enough to stop the rate limit issue?

Also is there a reason we didn't merge [this PR](https://github.com/transloadit/python-sdk/pull/14) instead?

**Comment by kvz** [comment]
To be honest I hadn’t realized this already had been submitted a fix for. I like that that PR takes into account the retryIn property, but it does seem to wait adding on delays until it is too late and they are already rate limited?

**Comment by kvz** [comment]
Got it, the. Let’s revert this PR and merge that one 👌

**Comment by ifedapoolarewaju** [comment]
released v0.2.0 https://github.com/transloadit/python-sdk/releases/tag/v0.2.0

It's a breaking change since we've dropped support for Python versions < 3.7 since the last release

**Pull request merged**
