### PR TITLE
Add sha384 to sig auth

### PR DESCRIPTION
**Pull request by cdr-chakotay**
Needed changes for signature authentication makeover. 

Have had no rights in the repo, providing the patch like this now :) 

@arnaudlimbourg @Acconut

### CODE REVIEW

**Comment by arnaudlimbourg** [comment]
@cdr-chakotay thanks!

Should there be support for more hashing algorithms? I'm wondering about the potential proliferation of boolean flags :)

**Comment by cdr-chakotay** [comment]
> @cdr-chakotay thanks!
> 
> Should there be support for more hashing algorithms? I'm wondering about the potential proliferation of boolean flags :)

We are currently moving away from SHA1 to SHA384. To avoid issues during the transit I wanted the users to be able to fall back to SHA1 in case of emergency. This is why I added the flag :)

**Comment by Acconut** [comment]
I agree with @arnaudlimbourg. If we add an option to control the signature algorithm, it is better to have a non-boolean value for forward compatibility. Something like `signature_algorithm = 'sha1' | 'sha384'`

**Comment by arnaudlimbourg** [comment]
an Enum could work here, not sure whether it would add much value.

**Comment by cdr-chakotay** [comment]
We can also just swap to SHA384, as the current discussion lines out that it should not have a negative effect.

**Comment by Acconut** [comment]
> We can also just swap to SHA384, as the current discussion lines out that it should not have a negative effect.

Yes, we have chosen that approach for most other SDKs now.

**Comment by cdr-chakotay** [comment]
Yeah, okay will update the PR is on my to-do :)

**Comment by cdr-chakotay** [comment]
Hey any updates regarding this :)

**Comment by Acconut** [comment]
I just added you as a maintainer to this repo. Did it work?

**Comment by cdr-chakotay** [comment]
Yeah, worked out :) Do we want to merge this ?

**Review by Acconut — COMMENTED** [review]
The change itself looks good, but I am a bit surprised that no changes to tests are needed to make CI pass. Do we not have any tests covering signature generation?

**Comment by Acconut** [comment]
Feel free to give it a try!

**Comment by cdr-chakotay** [comment]
Migrated to internal PR [27](https://github.com/transloadit/python-sdk/pull/27)

**Pull request closed without merging**
